repos:
  # general stuff
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.0.1
    hooks:
      # Git style
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-vcs-permalinks
        exclude: README.md
      - id: forbid-new-submodules
      - id: no-commit-to-branch

      # Common errors
      - id: end-of-file-fixer
        exclude: .*\.patch
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: .*\.patch
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-executables-have-shebangs

  # markdown
  - repo: https://github.com/markdownlint/markdownlint.git
    rev: 0b006db2722db937dfdf1d842c1b410b69d3e41f
    hooks:
      - id: markdownlint_docker

  # OpenEmbedded Styleguide
  - repo: https://github.com/priv-kweihmann/oelint-adv.git
    rev: 3.7.1
    hooks:
      - id: oelint-adv
        args:
          [
            --nowarn,
            --noinfo,
            --quiet,
            --relpaths,
            --suppress=oelint.task.nocopy,
          ]
