IOTEDGE_OVERLAY_RUN_ROOT_DIR ?= "/data"
IOTEDGE_OVERLAY_RUN_LOWER_DIR ?= "/var/lib/iotedge"
IOTEDGE_OVERLAY_RUN_UPPER_DIR ?= "/data/iotedge/var/lib/iotedge"
IOTEDGE_OVERLAY_RUN_WORK_DIR ?= "/data/.overlay/iotedge-work/var/lib/iotedge"

ETC_OVERLAY_CONFIG_ROOT_DIR ?= "/data"
ETC_OVERLAY_CONFIG_LOWER_DIR ?= "/etc"
ETC_OVERLAY_CONFIG_UPPER_DIR ?= "/data/etc"
ETC_OVERLAY_CONFIG_WORK_DIR ?= "/data/.overlay/etc"
