# This file contains paths to be excluded from the factory reset
# Do not refer the paths to the overlayed filesystems (e.g. /etc/NetworkManager/system-connections)
# use the upperdir paths on the data partition instead (e.g. /data/os-customization/state/etc/NetworkManager/system-connections)

# Examples:
# /data/test.file
# /data/example-folder
# /data/os-customization/state/etc/NetworkManager/system-connections/end0.connection

# Exclude the factory-reset configuration file itself to avoid reconfigure on every reset
/data/os-customization/state/etc/factory-reset-excludes.conf
