#!/bin/bash

DATA_DIR="/data"
EXCLUDE_DIR="mender"

echo "Deleting all data in $DATA_DIR except for $EXCLUDE_DIR..."
find "$DATA_DIR" -mindepth 1 -maxdepth 1 ! -name "$EXCLUDE_DIR" -exec rm -rf {} \+
echo "Data deletion complete."

reboot
