#!/bin/sh
set -e

/usr/bin/nmcli dev set uap0 managed no
/usr/bin/ln -sf /etc/access-point.network.active /etc/systemd/network/access-point.network
/usr/bin/networkctl reload
/usr/bin/networkctl reconfigure uap0
