[keyfile]
unmanaged-devices=interface-name:usb_io_ctrl;interface-name:usb_ext1;interface-name:usb_ext2;interface-name:usb_ext3;interface-name:usb_ext4;interface-name:usb_ext5;interface-name:usb_ext6;interface-name:usb_ext7;interface-name:usb_ext8;
